#!/bin/bash
#SBATCH --nodes 1
#SBATCH --tasks-per-node 32 
#SBATCH --time 1:00:00

export PATH=$PATH:/home/matthak/.conda/envs/dock_M/bin

/home/matthak/.conda/envs/dock_M/bin/python -u ../../main.py -i input.ini -dock
