#!/bin/bash
#SBATCH --nodes 1
#SBATCH --tasks-per-node 32 
#SBATCH --time 1:00:00

module load 2021 ORCA/5.0.3-gompi-2021a

export ASE_ORCA_COMMAND='/sw/arch/Centos8/EB_production/2021/software/ORCA/5.0.3-gompi-2021a/bin/orca PREFIX.inp > PREFIX.out'

/home/matthak/.conda/envs/metal_dock/bin/python3 -u ../../src/metal_dock/main.py -i input.ini -dock
