#!/bin/bash
#SBATCH -N 1
#SBATCH --tasks-per-node=32
#SBATCH -t 4:00:00
#

module load 2021 AMS/2021.101-intelmpi

echo "== Starting run at $(date)"
echo "== Job ID: ${SLURM_JOBID}"
echo "== Node list: ${SLURM_NODELIST}"
echo "== Submit dir. : ${SLURM_SUBMIT_DIR}"
echo "== Scratch dir. : ${TMPDIR}"

/home/matthak/.conda/envs/MetPar/bin/python -u /home/matthak/AutoDock_GA_par/autodock_metal_GA/src/main.py -i input.ini -train

echo "== Run end at $(date)"

