site_name: MetalDock 
site_url: https://metal_dock_docs.com/

nav: 
  - Home: index.md  
  - Installation: installation.md
  - Run MetalDock: run.md
  - Input Parameters: input_parameters.md
  - Output: output.md
theme: readthedocs
