#!/bin/bash
#SBATCH --nodes 1
#SBATCH --tasks-per-node 32 
#SBATCH --time 1:00:00

module load 2021
module load Gaussian/g16.c01

/home/matthak/.conda/envs/MetPar/bin/python -u ../../main.py -i input.ini -dock
